/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zverya
 */
public class NewJFrame extends javax.swing.JFrame {
String question;
String answer;
String answer1;
String answer2;
String answer3;
int click=1;
int point=0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 96));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setToolTipText("");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTextArea2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextArea2MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 640, 96));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setToolTipText("");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTextArea3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextArea3MouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 640, 96));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setToolTipText("");
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTextArea4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextArea4MouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 288, 640, 96));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setToolTipText("");
        jTextArea5.setWrapStyleWord(true);
        jTextArea5.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTextArea5AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTextArea5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextArea5MouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 384, 640, 96));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void questionreplay (){
    click=click+1;
   if(click==2){
    jTextArea1.setText("Каким образом ты зарабатываешь себе на жизнь? ");
    jTextArea2.setText("Ну как - я работаю менеджером по продаже мобильных телефонов… Зарплата небольшая, конечно, но на жизнь хватает.");
    jTextArea3.setText("Вечерами я езжу по улицам города на своем мопеде, сшибаю старушек монтировкой и отбираю у них авоськи с пустыми бутылками.");
    jTextArea4.setText("Видел на Красной площади чувака с плакатом \"Экстази: оптом и в розницу. Дешево!\"? Так вот это я был…");
    jTextArea5.setText("Военные тестируют на мне образцы нового бактериологического оружия. Просто бешенные бабки! А за позеленевшие яйца, отвалившийся член и вытекшие глаза они доплачивают мне отдельно…");
   }
    if(click==3){
    jTextArea1.setText("Вспомни-ка свой самый безбашенный поступок, который ты сделал на спор.");
    jTextArea2.setText("Однажды я на спор съел целиком журнал \"Хулиган\".");
    jTextArea3.setText("Покурить ногтей пенсионерки Зои Никитичны - это круто!");
    jTextArea4.setText("Как-то раз на первом ку рсе я нарисовал краской дневного свечения на двери деканата десять совокупляющихся бегемотиков. Будете проезжать мимо нашей воинской части на Новой Земле - заходите…");
    jTextArea5.setText("Хех, помню сижу я за штурвалом боинга, а впереди по курсу - Международный Торговый Центр…");
   }  
    if(click==4){
    jTextArea1.setText("Как ты провел вчерашний вечер? ");
    jTextArea2.setText("Вечером я лазал по Сети, в поисках порнографии с Натальей Орейро в главной роли. ");
    jTextArea3.setText("Весь вчерашний вечер я провел лежа, уткнувшись лицом в асфальт, руки за головой, пока дружелюбные омоновцы били меня сапогами по почкам.");
    jTextArea4.setText("Как провел…как провел….неважно как! В следующий раз буду брать больше вазелина и не разрешу привязывать себя к кровати колючей проволокой…");
    jTextArea5.setText("Ой, мля! Огуречный рассол сюда! И капельницу с физраствором! Быстро!!!");
   }
    if(click==5){
    jTextArea1.setText("Что написано на твоей майке?");
    jTextArea2.setText("Adidas ");
    jTextArea3.setText("Это я убил Лору Палмер…");
    jTextArea4.setText("Менты - козлы!");
    jTextArea5.setText("Я - гений! Всем сосать!!!");
   } 
    if(click==6){
    jTextArea1.setText("В каком виде ты пришел на выпускной школьный экзамен по алгебре?");
    jTextArea2.setText("В костюме с цветочком в петлице, тщательно начищенных туфлях и белоснежной рубашке. Экзамен, профессор, для меня всегда праздник… ");
    jTextArea3.setText("Кожаная куртка с заклепками, гриндера, зеленый ирокез, на тыльной стороне ладони у меня был вытатуирован портерт Че Гевары, а на шее висела шестикилограммовая стальная цепь с перевернутым крестом.");
    jTextArea4.setText("Высокие сапоги на платформе, пластиковая юбочка, вызывающий макияж. Фиг знает, почему я трояк получил…");
    jTextArea5.setText("На выпускной школьный экзамен по алгебре я вообще не пришел - в то время я проходил курс электрошоковой терапии в психиатрической лечебнице N128, куда меня упекли за то, что я целыми днями бегал по городу и красил воробьев в кислотные цвета.");
   } 
    if(click==7){
    jTextArea1.setText("Что бы ты сделал, если бы был Богом и мог все? ");
    jTextArea2.setText("Э-м-м… Ну сделал бы всех людей счастливыми. Или нет - я бы лучше переспал с Катькой из второго подъезда.");
    jTextArea3.setText("Дал бы каждому человеку по две печени. Одну - для повседневной жизни. А другую - для мрачных пьянок и оргий. ");
    jTextArea4.setText("Я бы сделал так, чтобы на Земле жили люди, разделенные на двадцать пять полов вместо двух. Чтобы, например, особь седьмого пола могла заниматься сексом с особью двадцать третьего пола и умирала бы только от одного прикосновения к особи тринадцатого пола. Вот вы, блин, помучаетесь…хе-хе…");
    jTextArea5.setText("Я бы пошел к Дьяволу с пятью-шестью бутылочками пивка: разбираться по понятиям…");
    }
   if(click==8){
    jTextArea1.setText("РЕЗУЛЬТАТЫ ");
    if(point<=20){
    jTextArea2.setText("Лох\n" +
"Хех, браза, все конечно понятно: тише едешь - дальше будешь и все такое, но уж слишком ты большой зануда! Попробуй что-нибудь изменить в своей жизни: начни бухать, поливать мамины цветы китайским супер-клеем и коллекционировать ядовитых лягушек. Вот увидишь - не пройдет и месяца, как люди к тебе потянутся…потными, волосатыми руками…");    
    jTextArea3.setText("");
    jTextArea4.setText("");
    jTextArea5.setText("");
    }
    if((21<=point)&(point<=60)){
    jTextArea2.setText("Сексуально-озабоченный фрик\n" +
"В целом достойно. Думаю, тебе не слабо будет подарить своей девчонке на восьмое марта видеокассету с записью твоих же похождений по борделям нашей необъятной страны. Или, напившись сиропа от кашля, прыгнуть с зонтиком с Останкинской телебашни, а потом мастурбировать на лету и распевать гимн Советского Союза на японском языке. Только вот мой тебе совет: перестань жрать кислоту, а не то скоро у тебя перестанет стоять…совсем.");
    jTextArea3.setText("");
    jTextArea4.setText("");
    jTextArea5.setText("");
    }
    if(61<=point){
     jTextArea2.setText("Крутой экстремал\n" +
"Респект, чувак. Ты, блин, экстремал-экстремал-экстремалище. Жить тебе осталось месяца три-четыре, так что самое время сейчас присмотреть уютное местечко на кладбище. Опять же рекомендую носить герметичную одежду: комбинезон или что-нибудь подобное - так тебя будет легче хоронить. А то, знаешь ли, очень муторно бывает собирать ошметки, оставшиеся от перца, который решил побриться циркулярной пилой.");   
    jTextArea3.setText("");
    jTextArea4.setText("");
    jTextArea5.setText("");
    }
    } 
}
    
    private void jTextArea1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea1AncestorAdded
jTextArea1.setText("Что сказала тебе твоя девушка после вашего последнего с ней секса? ");
    }//GEN-LAST:event_jTextArea1AncestorAdded

    private void jTextArea2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea2AncestorAdded
    jTextArea2.setText("Сладкий, это было просто чудесно!");
    }//GEN-LAST:event_jTextArea2AncestorAdded

    private void jTextArea3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea3AncestorAdded
      jTextArea3.setText("Значит так, пацан, за все про все с тебя штука двести…");
    }//GEN-LAST:event_jTextArea3AncestorAdded

    private void jTextArea4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea4AncestorAdded
   jTextArea4.setText("Да, любимый! А теперь давай подвесим тебя к потолку за соски и колечко в мошонке! Ну включай же скорее стробоскоп и ту пластинку с детройт-техно, чтобы никто не услышал твоих криков, а я пока пристегну искусственный член.");
    }//GEN-LAST:event_jTextArea4AncestorAdded

    private void jTextArea5AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTextArea5AncestorAdded
     jTextArea5.setText("Милый, давай в следующий раз ты не будешь подключать к мозгу электроды и делать себе инъекцию адренохрома! Тебе, конечно, кайфово дергаться и пускать пену изо рта во время секса, но меня мама воспитывала в более консервативных традициях.");
    }//GEN-LAST:event_jTextArea5AncestorAdded

    private void jTextArea2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea2MouseReleased
     questionreplay ();
     switch(click){
         case 1:
         case 2:
         case 5:
         case 6:
         case 7:
         point+=0;
         break;
         case 3:
         case 4:
         point+=1;
         break;
                     
     }
    }//GEN-LAST:event_jTextArea2MouseReleased

    private void jTextArea3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea3MouseReleased
      questionreplay ();
      switch(click){
      case 1:
      case 7:
      point+=1;
      break;
      case 2:
      case 3:
      case 5:
      point+=2;
      break;
      case 4:
      case 6:
      point+=3;
      break;
      }
    }//GEN-LAST:event_jTextArea3MouseReleased

    private void jTextArea4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea4MouseReleased
       questionreplay ();
       switch(click){
       case 1:
       point+=2;
       break;
       case 2:
       case 3:
       case 5:
       point+=3;
       break;
       case 7:
       point+=4;
       break;
       case 4:
       case 6:
       point+=5;
       break;
       
       }
    }//GEN-LAST:event_jTextArea4MouseReleased

    private void jTextArea5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea5MouseReleased
       questionreplay ();
      switch(click){
       case 1:
       case 2:
       case 3:
       point+=4;
       break;
       case 5:
       case 7:
       point+=5;
       break;
       case 6:
       point+=6;
       break;
       case 4:
       point+=7;
       break;
       
      }
    }//GEN-LAST:event_jTextArea5MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    // End of variables declaration//GEN-END:variables
}
