/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author podkolzinsergey
 */
public class NewJFrame extends javax.swing.JFrame {
int month;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jTextField1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 143, 148));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(jTextField1.getText().equals("1")){
    jLabel1.setText("Январь");
}
else if(jTextField1.getText().equals("2")){
        jLabel1.setText("Ферваль");
    }
            else if(jTextField1.getText().equals("3")){
            jLabel1.setText("Март");
        }
            else if(jTextField1.getText().equals("4")){
            jLabel1.setText("Апрель");
        }
            else if(jTextField1.getText().equals("5")){
            jLabel1.setText("Май");
        }
            else if(jTextField1.getText().equals("6")){
            jLabel1.setText("Июнь");
        }
            else if(jTextField1.getText().equals("7")){
            jLabel1.setText("Июль");
        }
            else if(jTextField1.getText().equals("8")){
            jLabel1.setText("Август");
        }
            else if(jTextField1.getText().equals("9")){
            jLabel1.setText("Сентябрь");
        }
            else if(jTextField1.getText().equals("10")){
            jLabel1.setText("Октябрь");
        }
            else if(jTextField1.getText().equals("11")){
            jLabel1.setText("Ноябрь");
        }
            else if(jTextField1.getText().equals("12")){
            jLabel1.setText("Декабрь");
        }
            else
            jLabel1.setText("Ошибка");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
       switch(jTextField1.getText()){
         case "1":
         jLabel1.setText("Январь");
         break;
         case "2":
         jLabel1.setText("Ферваль");
         break;
         case "3":
         jLabel1.setText("Март");
         break;
         case "4":
         jLabel1.setText("Апрель");
         break;
         case "5":
         jLabel1.setText("Май");
         break;
         case "6":
         jLabel1.setText("Июнь");
         break;
         case "7":
         jLabel1.setText("Июль");
         break;
         case "8":
         jLabel1.setText("Август");
         break;
         case "9":
         jLabel1.setText("Сентябрь");
         break;
         case "10":
         jLabel1.setText("Октябрь");
         break;
         case "11":
         jLabel1.setText("Ноябрь");
         break;
         case "12":
         jLabel1.setText("Декабрь");
         break;
      default: jLabel1.setText("Ошибка");
         break;
          
            
 }
        
     
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
